// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservasCore6.Data;

#nullable disable

namespace ReservasCore6.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReservasCore6.Models.Hotel", b =>
                {
                    b.Property<int>("IdHotel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHotel"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroHabitaciones")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHotel");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            IdHotel = 1,
                            Activo = true,
                            Descripcion = "Descripcion 1",
                            Latitud = 0.64243833121569482,
                            Longitud = 0.3701043890196597,
                            Nombre = "Hotel 1",
                            NumeroHabitaciones = 95,
                            Pais = "Pais 1"
                        },
                        new
                        {
                            IdHotel = 2,
                            Activo = true,
                            Descripcion = "Descripcion 2",
                            Latitud = 0.12490440223962629,
                            Longitud = 0.33161098774873465,
                            Nombre = "Hotel 2",
                            NumeroHabitaciones = 89,
                            Pais = "Pais 2"
                        },
                        new
                        {
                            IdHotel = 3,
                            Activo = true,
                            Descripcion = "Descripcion 3",
                            Latitud = 0.24378729261328114,
                            Longitud = 0.39790944964416908,
                            Nombre = "Hotel 3",
                            NumeroHabitaciones = 22,
                            Pais = "Pais 3"
                        },
                        new
                        {
                            IdHotel = 4,
                            Activo = true,
                            Descripcion = "Descripcion 4",
                            Latitud = 0.081594966052063067,
                            Longitud = 0.7003974993458385,
                            Nombre = "Hotel 4",
                            NumeroHabitaciones = 73,
                            Pais = "Pais 4"
                        },
                        new
                        {
                            IdHotel = 5,
                            Activo = true,
                            Descripcion = "Descripcion 5",
                            Latitud = 0.68895171171535274,
                            Longitud = 0.19478295474504237,
                            Nombre = "Hotel 5",
                            NumeroHabitaciones = 12,
                            Pais = "Pais 5"
                        },
                        new
                        {
                            IdHotel = 6,
                            Activo = true,
                            Descripcion = "Descripcion 6",
                            Latitud = 0.077893811461345996,
                            Longitud = 0.96028868612359297,
                            Nombre = "Hotel 6",
                            NumeroHabitaciones = 64,
                            Pais = "Pais 6"
                        },
                        new
                        {
                            IdHotel = 7,
                            Activo = true,
                            Descripcion = "Descripcion 7",
                            Latitud = 0.46497881711737721,
                            Longitud = 0.9380126851824464,
                            Nombre = "Hotel 7",
                            NumeroHabitaciones = 97,
                            Pais = "Pais 7"
                        },
                        new
                        {
                            IdHotel = 8,
                            Activo = true,
                            Descripcion = "Descripcion 8",
                            Latitud = 0.84352081522247713,
                            Longitud = 0.94493852152794688,
                            Nombre = "Hotel 8",
                            NumeroHabitaciones = 92,
                            Pais = "Pais 8"
                        },
                        new
                        {
                            IdHotel = 9,
                            Activo = true,
                            Descripcion = "Descripcion 9",
                            Latitud = 0.023770903007587552,
                            Longitud = 0.98817230775190534,
                            Nombre = "Hotel 9",
                            NumeroHabitaciones = 57,
                            Pais = "Pais 9"
                        },
                        new
                        {
                            IdHotel = 10,
                            Activo = true,
                            Descripcion = "Descripcion 10",
                            Latitud = 0.43426541936919616,
                            Longitud = 0.12172822212512735,
                            Nombre = "Hotel 10",
                            NumeroHabitaciones = 53,
                            Pais = "Pais 10"
                        },
                        new
                        {
                            IdHotel = 11,
                            Activo = true,
                            Descripcion = "Descripcion 11",
                            Latitud = 0.45900495217705251,
                            Longitud = 0.15964123448259893,
                            Nombre = "Hotel 11",
                            NumeroHabitaciones = 16,
                            Pais = "Pais 11"
                        },
                        new
                        {
                            IdHotel = 12,
                            Activo = true,
                            Descripcion = "Descripcion 12",
                            Latitud = 0.65484286555521232,
                            Longitud = 0.23580690083553135,
                            Nombre = "Hotel 12",
                            NumeroHabitaciones = 14,
                            Pais = "Pais 12"
                        },
                        new
                        {
                            IdHotel = 13,
                            Activo = true,
                            Descripcion = "Descripcion 13",
                            Latitud = 0.13560203482038524,
                            Longitud = 0.78196826697148847,
                            Nombre = "Hotel 13",
                            NumeroHabitaciones = 80,
                            Pais = "Pais 13"
                        },
                        new
                        {
                            IdHotel = 14,
                            Activo = true,
                            Descripcion = "Descripcion 14",
                            Latitud = 0.065785391799705661,
                            Longitud = 0.49204568149795636,
                            Nombre = "Hotel 14",
                            NumeroHabitaciones = 34,
                            Pais = "Pais 14"
                        },
                        new
                        {
                            IdHotel = 15,
                            Activo = true,
                            Descripcion = "Descripcion 15",
                            Latitud = 0.56261359966096591,
                            Longitud = 0.11223029625009218,
                            Nombre = "Hotel 15",
                            NumeroHabitaciones = 83,
                            Pais = "Pais 15"
                        },
                        new
                        {
                            IdHotel = 16,
                            Activo = true,
                            Descripcion = "Descripcion 16",
                            Latitud = 0.91305158843700884,
                            Longitud = 0.45560135746739994,
                            Nombre = "Hotel 16",
                            NumeroHabitaciones = 22,
                            Pais = "Pais 16"
                        },
                        new
                        {
                            IdHotel = 17,
                            Activo = true,
                            Descripcion = "Descripcion 17",
                            Latitud = 0.9600096383047978,
                            Longitud = 0.76323497774875027,
                            Nombre = "Hotel 17",
                            NumeroHabitaciones = 8,
                            Pais = "Pais 17"
                        },
                        new
                        {
                            IdHotel = 18,
                            Activo = true,
                            Descripcion = "Descripcion 18",
                            Latitud = 0.8975014684217254,
                            Longitud = 0.17228393769223238,
                            Nombre = "Hotel 18",
                            NumeroHabitaciones = 81,
                            Pais = "Pais 18"
                        },
                        new
                        {
                            IdHotel = 19,
                            Activo = true,
                            Descripcion = "Descripcion 19",
                            Latitud = 0.10212935949494095,
                            Longitud = 0.95209656367494611,
                            Nombre = "Hotel 19",
                            NumeroHabitaciones = 91,
                            Pais = "Pais 19"
                        },
                        new
                        {
                            IdHotel = 20,
                            Activo = true,
                            Descripcion = "Descripcion 20",
                            Latitud = 0.48984276617701505,
                            Longitud = 0.32957335888750328,
                            Nombre = "Hotel 20",
                            NumeroHabitaciones = 65,
                            Pais = "Pais 20"
                        },
                        new
                        {
                            IdHotel = 21,
                            Activo = true,
                            Descripcion = "Descripcion 21",
                            Latitud = 0.32717762187381993,
                            Longitud = 0.41997533092348072,
                            Nombre = "Hotel 21",
                            NumeroHabitaciones = 22,
                            Pais = "Pais 21"
                        },
                        new
                        {
                            IdHotel = 22,
                            Activo = true,
                            Descripcion = "Descripcion 22",
                            Latitud = 0.86167116304173164,
                            Longitud = 0.20060904857454487,
                            Nombre = "Hotel 22",
                            NumeroHabitaciones = 33,
                            Pais = "Pais 22"
                        },
                        new
                        {
                            IdHotel = 23,
                            Activo = true,
                            Descripcion = "Descripcion 23",
                            Latitud = 0.25623191892951891,
                            Longitud = 0.98092735496843775,
                            Nombre = "Hotel 23",
                            NumeroHabitaciones = 14,
                            Pais = "Pais 23"
                        },
                        new
                        {
                            IdHotel = 24,
                            Activo = true,
                            Descripcion = "Descripcion 24",
                            Latitud = 0.96409126191970929,
                            Longitud = 0.33678284152328886,
                            Nombre = "Hotel 24",
                            NumeroHabitaciones = 17,
                            Pais = "Pais 24"
                        },
                        new
                        {
                            IdHotel = 25,
                            Activo = true,
                            Descripcion = "Descripcion 25",
                            Latitud = 0.56662071184814844,
                            Longitud = 0.86814019789028363,
                            Nombre = "Hotel 25",
                            NumeroHabitaciones = 28,
                            Pais = "Pais 25"
                        },
                        new
                        {
                            IdHotel = 26,
                            Activo = true,
                            Descripcion = "Descripcion 26",
                            Latitud = 0.9986843187791995,
                            Longitud = 0.25697154819830914,
                            Nombre = "Hotel 26",
                            NumeroHabitaciones = 15,
                            Pais = "Pais 26"
                        },
                        new
                        {
                            IdHotel = 27,
                            Activo = true,
                            Descripcion = "Descripcion 27",
                            Latitud = 0.88630480303091841,
                            Longitud = 0.68850695203459877,
                            Nombre = "Hotel 27",
                            NumeroHabitaciones = 64,
                            Pais = "Pais 27"
                        },
                        new
                        {
                            IdHotel = 28,
                            Activo = true,
                            Descripcion = "Descripcion 28",
                            Latitud = 0.20558441340285727,
                            Longitud = 0.19271175733803425,
                            Nombre = "Hotel 28",
                            NumeroHabitaciones = 76,
                            Pais = "Pais 28"
                        },
                        new
                        {
                            IdHotel = 29,
                            Activo = true,
                            Descripcion = "Descripcion 29",
                            Latitud = 0.18586750581258116,
                            Longitud = 0.63870050685239821,
                            Nombre = "Hotel 29",
                            NumeroHabitaciones = 53,
                            Pais = "Pais 29"
                        },
                        new
                        {
                            IdHotel = 30,
                            Activo = true,
                            Descripcion = "Descripcion 30",
                            Latitud = 0.41908916401069374,
                            Longitud = 0.90690516374630537,
                            Nombre = "Hotel 30",
                            NumeroHabitaciones = 62,
                            Pais = "Pais 30"
                        },
                        new
                        {
                            IdHotel = 31,
                            Activo = true,
                            Descripcion = "Descripcion 31",
                            Latitud = 0.2053605821849952,
                            Longitud = 0.50751270470939536,
                            Nombre = "Hotel 31",
                            NumeroHabitaciones = 44,
                            Pais = "Pais 31"
                        },
                        new
                        {
                            IdHotel = 32,
                            Activo = true,
                            Descripcion = "Descripcion 32",
                            Latitud = 0.6567455315464612,
                            Longitud = 0.72758981863776973,
                            Nombre = "Hotel 32",
                            NumeroHabitaciones = 22,
                            Pais = "Pais 32"
                        },
                        new
                        {
                            IdHotel = 33,
                            Activo = true,
                            Descripcion = "Descripcion 33",
                            Latitud = 0.020551597027549828,
                            Longitud = 0.47348601248496203,
                            Nombre = "Hotel 33",
                            NumeroHabitaciones = 6,
                            Pais = "Pais 33"
                        },
                        new
                        {
                            IdHotel = 34,
                            Activo = true,
                            Descripcion = "Descripcion 34",
                            Latitud = 0.23085864367567288,
                            Longitud = 0.3582107520752662,
                            Nombre = "Hotel 34",
                            NumeroHabitaciones = 14,
                            Pais = "Pais 34"
                        },
                        new
                        {
                            IdHotel = 35,
                            Activo = true,
                            Descripcion = "Descripcion 35",
                            Latitud = 0.85208090527620506,
                            Longitud = 0.80238303317417992,
                            Nombre = "Hotel 35",
                            NumeroHabitaciones = 46,
                            Pais = "Pais 35"
                        },
                        new
                        {
                            IdHotel = 36,
                            Activo = true,
                            Descripcion = "Descripcion 36",
                            Latitud = 0.118883948049194,
                            Longitud = 0.26675312002784946,
                            Nombre = "Hotel 36",
                            NumeroHabitaciones = 94,
                            Pais = "Pais 36"
                        },
                        new
                        {
                            IdHotel = 37,
                            Activo = true,
                            Descripcion = "Descripcion 37",
                            Latitud = 0.74011974405267,
                            Longitud = 0.22349403394397394,
                            Nombre = "Hotel 37",
                            NumeroHabitaciones = 39,
                            Pais = "Pais 37"
                        },
                        new
                        {
                            IdHotel = 38,
                            Activo = true,
                            Descripcion = "Descripcion 38",
                            Latitud = 0.60758409328970031,
                            Longitud = 0.64423851906988971,
                            Nombre = "Hotel 38",
                            NumeroHabitaciones = 49,
                            Pais = "Pais 38"
                        },
                        new
                        {
                            IdHotel = 39,
                            Activo = true,
                            Descripcion = "Descripcion 39",
                            Latitud = 0.50308649401663952,
                            Longitud = 0.083358731258613261,
                            Nombre = "Hotel 39",
                            NumeroHabitaciones = 44,
                            Pais = "Pais 39"
                        },
                        new
                        {
                            IdHotel = 40,
                            Activo = true,
                            Descripcion = "Descripcion 40",
                            Latitud = 0.005546677537339062,
                            Longitud = 0.016930125902463899,
                            Nombre = "Hotel 40",
                            NumeroHabitaciones = 69,
                            Pais = "Pais 40"
                        },
                        new
                        {
                            IdHotel = 41,
                            Activo = true,
                            Descripcion = "Descripcion 41",
                            Latitud = 0.98602362533215082,
                            Longitud = 0.27910793407968548,
                            Nombre = "Hotel 41",
                            NumeroHabitaciones = 38,
                            Pais = "Pais 41"
                        },
                        new
                        {
                            IdHotel = 42,
                            Activo = true,
                            Descripcion = "Descripcion 42",
                            Latitud = 0.7451362753713463,
                            Longitud = 0.097589957001154692,
                            Nombre = "Hotel 42",
                            NumeroHabitaciones = 90,
                            Pais = "Pais 42"
                        },
                        new
                        {
                            IdHotel = 43,
                            Activo = true,
                            Descripcion = "Descripcion 43",
                            Latitud = 0.012255406173518169,
                            Longitud = 0.5197979172738546,
                            Nombre = "Hotel 43",
                            NumeroHabitaciones = 35,
                            Pais = "Pais 43"
                        },
                        new
                        {
                            IdHotel = 44,
                            Activo = true,
                            Descripcion = "Descripcion 44",
                            Latitud = 0.49914470218149043,
                            Longitud = 0.25746688600481127,
                            Nombre = "Hotel 44",
                            NumeroHabitaciones = 71,
                            Pais = "Pais 44"
                        },
                        new
                        {
                            IdHotel = 45,
                            Activo = true,
                            Descripcion = "Descripcion 45",
                            Latitud = 0.43973334460617297,
                            Longitud = 0.62712413824686486,
                            Nombre = "Hotel 45",
                            NumeroHabitaciones = 85,
                            Pais = "Pais 45"
                        },
                        new
                        {
                            IdHotel = 46,
                            Activo = true,
                            Descripcion = "Descripcion 46",
                            Latitud = 0.42802288101002695,
                            Longitud = 0.97982966890371526,
                            Nombre = "Hotel 46",
                            NumeroHabitaciones = 47,
                            Pais = "Pais 46"
                        },
                        new
                        {
                            IdHotel = 47,
                            Activo = true,
                            Descripcion = "Descripcion 47",
                            Latitud = 0.015520916035647425,
                            Longitud = 0.96489773766590692,
                            Nombre = "Hotel 47",
                            NumeroHabitaciones = 56,
                            Pais = "Pais 47"
                        },
                        new
                        {
                            IdHotel = 48,
                            Activo = true,
                            Descripcion = "Descripcion 48",
                            Latitud = 0.56654956601933559,
                            Longitud = 0.81861360606393063,
                            Nombre = "Hotel 48",
                            NumeroHabitaciones = 12,
                            Pais = "Pais 48"
                        },
                        new
                        {
                            IdHotel = 49,
                            Activo = true,
                            Descripcion = "Descripcion 49",
                            Latitud = 0.714790704448242,
                            Longitud = 0.44489798765329081,
                            Nombre = "Hotel 49",
                            NumeroHabitaciones = 12,
                            Pais = "Pais 49"
                        },
                        new
                        {
                            IdHotel = 50,
                            Activo = true,
                            Descripcion = "Descripcion 50",
                            Latitud = 0.083630928230477575,
                            Longitud = 0.49266680998080592,
                            Nombre = "Hotel 50",
                            NumeroHabitaciones = 65,
                            Pais = "Pais 50"
                        },
                        new
                        {
                            IdHotel = 51,
                            Activo = true,
                            Descripcion = "Descripcion 51",
                            Latitud = 0.12093237585944294,
                            Longitud = 0.055263421511637767,
                            Nombre = "Hotel 51",
                            NumeroHabitaciones = 86,
                            Pais = "Pais 51"
                        },
                        new
                        {
                            IdHotel = 52,
                            Activo = true,
                            Descripcion = "Descripcion 52",
                            Latitud = 0.71624688623950927,
                            Longitud = 0.47172307631997656,
                            Nombre = "Hotel 52",
                            NumeroHabitaciones = 63,
                            Pais = "Pais 52"
                        },
                        new
                        {
                            IdHotel = 53,
                            Activo = true,
                            Descripcion = "Descripcion 53",
                            Latitud = 0.25849831989074645,
                            Longitud = 0.32372304421472631,
                            Nombre = "Hotel 53",
                            NumeroHabitaciones = 44,
                            Pais = "Pais 53"
                        },
                        new
                        {
                            IdHotel = 54,
                            Activo = true,
                            Descripcion = "Descripcion 54",
                            Latitud = 0.23171563720318644,
                            Longitud = 0.77648243005569273,
                            Nombre = "Hotel 54",
                            NumeroHabitaciones = 97,
                            Pais = "Pais 54"
                        },
                        new
                        {
                            IdHotel = 55,
                            Activo = true,
                            Descripcion = "Descripcion 55",
                            Latitud = 0.70843977058552532,
                            Longitud = 0.32977785717166963,
                            Nombre = "Hotel 55",
                            NumeroHabitaciones = 80,
                            Pais = "Pais 55"
                        },
                        new
                        {
                            IdHotel = 56,
                            Activo = true,
                            Descripcion = "Descripcion 56",
                            Latitud = 0.44332064543335803,
                            Longitud = 0.31081664883797122,
                            Nombre = "Hotel 56",
                            NumeroHabitaciones = 41,
                            Pais = "Pais 56"
                        },
                        new
                        {
                            IdHotel = 57,
                            Activo = true,
                            Descripcion = "Descripcion 57",
                            Latitud = 0.0017592149893990161,
                            Longitud = 0.80464490384488363,
                            Nombre = "Hotel 57",
                            NumeroHabitaciones = 94,
                            Pais = "Pais 57"
                        },
                        new
                        {
                            IdHotel = 58,
                            Activo = true,
                            Descripcion = "Descripcion 58",
                            Latitud = 0.35898497369954974,
                            Longitud = 0.99474691546040694,
                            Nombre = "Hotel 58",
                            NumeroHabitaciones = 99,
                            Pais = "Pais 58"
                        },
                        new
                        {
                            IdHotel = 59,
                            Activo = true,
                            Descripcion = "Descripcion 59",
                            Latitud = 0.20797832633851088,
                            Longitud = 0.94820868615947507,
                            Nombre = "Hotel 59",
                            NumeroHabitaciones = 31,
                            Pais = "Pais 59"
                        },
                        new
                        {
                            IdHotel = 60,
                            Activo = true,
                            Descripcion = "Descripcion 60",
                            Latitud = 0.34879179625436385,
                            Longitud = 0.93544930331383169,
                            Nombre = "Hotel 60",
                            NumeroHabitaciones = 97,
                            Pais = "Pais 60"
                        },
                        new
                        {
                            IdHotel = 61,
                            Activo = true,
                            Descripcion = "Descripcion 61",
                            Latitud = 0.25742161301396438,
                            Longitud = 0.019417986139927623,
                            Nombre = "Hotel 61",
                            NumeroHabitaciones = 22,
                            Pais = "Pais 61"
                        },
                        new
                        {
                            IdHotel = 62,
                            Activo = true,
                            Descripcion = "Descripcion 62",
                            Latitud = 0.9204064533728239,
                            Longitud = 0.92500178508450892,
                            Nombre = "Hotel 62",
                            NumeroHabitaciones = 83,
                            Pais = "Pais 62"
                        },
                        new
                        {
                            IdHotel = 63,
                            Activo = true,
                            Descripcion = "Descripcion 63",
                            Latitud = 0.77185911383939765,
                            Longitud = 0.42186952043582082,
                            Nombre = "Hotel 63",
                            NumeroHabitaciones = 76,
                            Pais = "Pais 63"
                        },
                        new
                        {
                            IdHotel = 64,
                            Activo = true,
                            Descripcion = "Descripcion 64",
                            Latitud = 0.89594133571625456,
                            Longitud = 0.26948601803420869,
                            Nombre = "Hotel 64",
                            NumeroHabitaciones = 72,
                            Pais = "Pais 64"
                        },
                        new
                        {
                            IdHotel = 65,
                            Activo = true,
                            Descripcion = "Descripcion 65",
                            Latitud = 0.4027906858727357,
                            Longitud = 0.53963315040448823,
                            Nombre = "Hotel 65",
                            NumeroHabitaciones = 79,
                            Pais = "Pais 65"
                        },
                        new
                        {
                            IdHotel = 66,
                            Activo = true,
                            Descripcion = "Descripcion 66",
                            Latitud = 0.31971726859990046,
                            Longitud = 0.70835797226661368,
                            Nombre = "Hotel 66",
                            NumeroHabitaciones = 17,
                            Pais = "Pais 66"
                        },
                        new
                        {
                            IdHotel = 67,
                            Activo = true,
                            Descripcion = "Descripcion 67",
                            Latitud = 0.82491861711444636,
                            Longitud = 0.97081889064450888,
                            Nombre = "Hotel 67",
                            NumeroHabitaciones = 28,
                            Pais = "Pais 67"
                        },
                        new
                        {
                            IdHotel = 68,
                            Activo = true,
                            Descripcion = "Descripcion 68",
                            Latitud = 0.10315508721620925,
                            Longitud = 0.96600128531067686,
                            Nombre = "Hotel 68",
                            NumeroHabitaciones = 94,
                            Pais = "Pais 68"
                        },
                        new
                        {
                            IdHotel = 69,
                            Activo = true,
                            Descripcion = "Descripcion 69",
                            Latitud = 0.50236324287098111,
                            Longitud = 0.048079417013275783,
                            Nombre = "Hotel 69",
                            NumeroHabitaciones = 27,
                            Pais = "Pais 69"
                        },
                        new
                        {
                            IdHotel = 70,
                            Activo = true,
                            Descripcion = "Descripcion 70",
                            Latitud = 0.74751642016142616,
                            Longitud = 0.72567055793801616,
                            Nombre = "Hotel 70",
                            NumeroHabitaciones = 39,
                            Pais = "Pais 70"
                        },
                        new
                        {
                            IdHotel = 71,
                            Activo = true,
                            Descripcion = "Descripcion 71",
                            Latitud = 0.14083044497207253,
                            Longitud = 0.17868035103768021,
                            Nombre = "Hotel 71",
                            NumeroHabitaciones = 93,
                            Pais = "Pais 71"
                        },
                        new
                        {
                            IdHotel = 72,
                            Activo = true,
                            Descripcion = "Descripcion 72",
                            Latitud = 0.94236393647741101,
                            Longitud = 0.34188870552992201,
                            Nombre = "Hotel 72",
                            NumeroHabitaciones = 6,
                            Pais = "Pais 72"
                        },
                        new
                        {
                            IdHotel = 73,
                            Activo = true,
                            Descripcion = "Descripcion 73",
                            Latitud = 0.28257288175711748,
                            Longitud = 0.65665758490310555,
                            Nombre = "Hotel 73",
                            NumeroHabitaciones = 48,
                            Pais = "Pais 73"
                        },
                        new
                        {
                            IdHotel = 74,
                            Activo = true,
                            Descripcion = "Descripcion 74",
                            Latitud = 0.44823599156878147,
                            Longitud = 0.7982124780767279,
                            Nombre = "Hotel 74",
                            NumeroHabitaciones = 27,
                            Pais = "Pais 74"
                        },
                        new
                        {
                            IdHotel = 75,
                            Activo = true,
                            Descripcion = "Descripcion 75",
                            Latitud = 0.66260622503917543,
                            Longitud = 0.81794737081000835,
                            Nombre = "Hotel 75",
                            NumeroHabitaciones = 26,
                            Pais = "Pais 75"
                        },
                        new
                        {
                            IdHotel = 76,
                            Activo = true,
                            Descripcion = "Descripcion 76",
                            Latitud = 0.50165027065898815,
                            Longitud = 0.050043858191940127,
                            Nombre = "Hotel 76",
                            NumeroHabitaciones = 17,
                            Pais = "Pais 76"
                        },
                        new
                        {
                            IdHotel = 77,
                            Activo = true,
                            Descripcion = "Descripcion 77",
                            Latitud = 0.7721678103517513,
                            Longitud = 0.054281947120030538,
                            Nombre = "Hotel 77",
                            NumeroHabitaciones = 91,
                            Pais = "Pais 77"
                        },
                        new
                        {
                            IdHotel = 78,
                            Activo = true,
                            Descripcion = "Descripcion 78",
                            Latitud = 0.42509667614398294,
                            Longitud = 0.78275822903870251,
                            Nombre = "Hotel 78",
                            NumeroHabitaciones = 71,
                            Pais = "Pais 78"
                        },
                        new
                        {
                            IdHotel = 79,
                            Activo = true,
                            Descripcion = "Descripcion 79",
                            Latitud = 0.95758168728070159,
                            Longitud = 0.75096778651858986,
                            Nombre = "Hotel 79",
                            NumeroHabitaciones = 34,
                            Pais = "Pais 79"
                        },
                        new
                        {
                            IdHotel = 80,
                            Activo = true,
                            Descripcion = "Descripcion 80",
                            Latitud = 0.20672956011830124,
                            Longitud = 0.93268824601365663,
                            Nombre = "Hotel 80",
                            NumeroHabitaciones = 91,
                            Pais = "Pais 80"
                        },
                        new
                        {
                            IdHotel = 81,
                            Activo = true,
                            Descripcion = "Descripcion 81",
                            Latitud = 0.35769577402499919,
                            Longitud = 0.01622515107337108,
                            Nombre = "Hotel 81",
                            NumeroHabitaciones = 36,
                            Pais = "Pais 81"
                        },
                        new
                        {
                            IdHotel = 82,
                            Activo = true,
                            Descripcion = "Descripcion 82",
                            Latitud = 0.4446104114000029,
                            Longitud = 0.68590895878303815,
                            Nombre = "Hotel 82",
                            NumeroHabitaciones = 85,
                            Pais = "Pais 82"
                        },
                        new
                        {
                            IdHotel = 83,
                            Activo = true,
                            Descripcion = "Descripcion 83",
                            Latitud = 0.98654607104104697,
                            Longitud = 0.85126060959848682,
                            Nombre = "Hotel 83",
                            NumeroHabitaciones = 70,
                            Pais = "Pais 83"
                        },
                        new
                        {
                            IdHotel = 84,
                            Activo = true,
                            Descripcion = "Descripcion 84",
                            Latitud = 0.52301999669244092,
                            Longitud = 0.94553686187345143,
                            Nombre = "Hotel 84",
                            NumeroHabitaciones = 31,
                            Pais = "Pais 84"
                        },
                        new
                        {
                            IdHotel = 85,
                            Activo = true,
                            Descripcion = "Descripcion 85",
                            Latitud = 0.3064343702121205,
                            Longitud = 0.25846186807466631,
                            Nombre = "Hotel 85",
                            NumeroHabitaciones = 87,
                            Pais = "Pais 85"
                        },
                        new
                        {
                            IdHotel = 86,
                            Activo = true,
                            Descripcion = "Descripcion 86",
                            Latitud = 0.51330725972598557,
                            Longitud = 0.68966957385433381,
                            Nombre = "Hotel 86",
                            NumeroHabitaciones = 98,
                            Pais = "Pais 86"
                        },
                        new
                        {
                            IdHotel = 87,
                            Activo = true,
                            Descripcion = "Descripcion 87",
                            Latitud = 0.48511438887143454,
                            Longitud = 0.95815288754513916,
                            Nombre = "Hotel 87",
                            NumeroHabitaciones = 51,
                            Pais = "Pais 87"
                        },
                        new
                        {
                            IdHotel = 88,
                            Activo = true,
                            Descripcion = "Descripcion 88",
                            Latitud = 0.28811460321449645,
                            Longitud = 0.93470936744226851,
                            Nombre = "Hotel 88",
                            NumeroHabitaciones = 64,
                            Pais = "Pais 88"
                        },
                        new
                        {
                            IdHotel = 89,
                            Activo = true,
                            Descripcion = "Descripcion 89",
                            Latitud = 0.50905357395614625,
                            Longitud = 0.66961487277125786,
                            Nombre = "Hotel 89",
                            NumeroHabitaciones = 27,
                            Pais = "Pais 89"
                        },
                        new
                        {
                            IdHotel = 90,
                            Activo = true,
                            Descripcion = "Descripcion 90",
                            Latitud = 0.041418729644830177,
                            Longitud = 0.88948771839511731,
                            Nombre = "Hotel 90",
                            NumeroHabitaciones = 21,
                            Pais = "Pais 90"
                        },
                        new
                        {
                            IdHotel = 91,
                            Activo = true,
                            Descripcion = "Descripcion 91",
                            Latitud = 0.68306803597870092,
                            Longitud = 0.031370782838044398,
                            Nombre = "Hotel 91",
                            NumeroHabitaciones = 96,
                            Pais = "Pais 91"
                        },
                        new
                        {
                            IdHotel = 92,
                            Activo = true,
                            Descripcion = "Descripcion 92",
                            Latitud = 0.61181080078287653,
                            Longitud = 0.8715828567312548,
                            Nombre = "Hotel 92",
                            NumeroHabitaciones = 25,
                            Pais = "Pais 92"
                        },
                        new
                        {
                            IdHotel = 93,
                            Activo = true,
                            Descripcion = "Descripcion 93",
                            Latitud = 0.64362965214042234,
                            Longitud = 0.57872612058688699,
                            Nombre = "Hotel 93",
                            NumeroHabitaciones = 14,
                            Pais = "Pais 93"
                        },
                        new
                        {
                            IdHotel = 94,
                            Activo = true,
                            Descripcion = "Descripcion 94",
                            Latitud = 0.62457804096566683,
                            Longitud = 0.91892536583840279,
                            Nombre = "Hotel 94",
                            NumeroHabitaciones = 5,
                            Pais = "Pais 94"
                        },
                        new
                        {
                            IdHotel = 95,
                            Activo = true,
                            Descripcion = "Descripcion 95",
                            Latitud = 0.89747725102334919,
                            Longitud = 0.76264942334264119,
                            Nombre = "Hotel 95",
                            NumeroHabitaciones = 70,
                            Pais = "Pais 95"
                        },
                        new
                        {
                            IdHotel = 96,
                            Activo = true,
                            Descripcion = "Descripcion 96",
                            Latitud = 0.5049880718989429,
                            Longitud = 0.51662030299867279,
                            Nombre = "Hotel 96",
                            NumeroHabitaciones = 28,
                            Pais = "Pais 96"
                        },
                        new
                        {
                            IdHotel = 97,
                            Activo = true,
                            Descripcion = "Descripcion 97",
                            Latitud = 0.14434964748164436,
                            Longitud = 0.26358668512491146,
                            Nombre = "Hotel 97",
                            NumeroHabitaciones = 46,
                            Pais = "Pais 97"
                        },
                        new
                        {
                            IdHotel = 98,
                            Activo = true,
                            Descripcion = "Descripcion 98",
                            Latitud = 0.356444498073617,
                            Longitud = 0.26050099856368081,
                            Nombre = "Hotel 98",
                            NumeroHabitaciones = 58,
                            Pais = "Pais 98"
                        },
                        new
                        {
                            IdHotel = 99,
                            Activo = true,
                            Descripcion = "Descripcion 99",
                            Latitud = 0.21686591306847647,
                            Longitud = 0.31228798139474456,
                            Nombre = "Hotel 99",
                            NumeroHabitaciones = 50,
                            Pais = "Pais 99"
                        },
                        new
                        {
                            IdHotel = 100,
                            Activo = true,
                            Descripcion = "Descripcion 100",
                            Latitud = 0.80601437778788931,
                            Longitud = 0.3384511947194736,
                            Nombre = "Hotel 100",
                            NumeroHabitaciones = 39,
                            Pais = "Pais 100"
                        });
                });

            modelBuilder.Entity("ReservasCore6.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"), 1L, 1);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdHotel")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("NumeroHabitacion")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdHotel");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("ReservasCore6.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Apellidos = "apellido 1",
                            Direccion = "Direccion 1",
                            Email = "Email@dominio.com 1",
                            Nombre = "usuario 1"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Apellidos = "apellido 2",
                            Direccion = "Direccion 2",
                            Email = "Email@dominio.com 2",
                            Nombre = "usuario 2"
                        },
                        new
                        {
                            IdUsuario = 3,
                            Apellidos = "apellido 3",
                            Direccion = "Direccion 3",
                            Email = "Email@dominio.com 3",
                            Nombre = "usuario 3"
                        },
                        new
                        {
                            IdUsuario = 4,
                            Apellidos = "apellido 4",
                            Direccion = "Direccion 4",
                            Email = "Email@dominio.com 4",
                            Nombre = "usuario 4"
                        },
                        new
                        {
                            IdUsuario = 5,
                            Apellidos = "apellido 5",
                            Direccion = "Direccion 5",
                            Email = "Email@dominio.com 5",
                            Nombre = "usuario 5"
                        },
                        new
                        {
                            IdUsuario = 6,
                            Apellidos = "apellido 6",
                            Direccion = "Direccion 6",
                            Email = "Email@dominio.com 6",
                            Nombre = "usuario 6"
                        },
                        new
                        {
                            IdUsuario = 7,
                            Apellidos = "apellido 7",
                            Direccion = "Direccion 7",
                            Email = "Email@dominio.com 7",
                            Nombre = "usuario 7"
                        },
                        new
                        {
                            IdUsuario = 8,
                            Apellidos = "apellido 8",
                            Direccion = "Direccion 8",
                            Email = "Email@dominio.com 8",
                            Nombre = "usuario 8"
                        },
                        new
                        {
                            IdUsuario = 9,
                            Apellidos = "apellido 9",
                            Direccion = "Direccion 9",
                            Email = "Email@dominio.com 9",
                            Nombre = "usuario 9"
                        },
                        new
                        {
                            IdUsuario = 10,
                            Apellidos = "apellido 10",
                            Direccion = "Direccion 10",
                            Email = "Email@dominio.com 10",
                            Nombre = "usuario 10"
                        },
                        new
                        {
                            IdUsuario = 11,
                            Apellidos = "apellido 11",
                            Direccion = "Direccion 11",
                            Email = "Email@dominio.com 11",
                            Nombre = "usuario 11"
                        },
                        new
                        {
                            IdUsuario = 12,
                            Apellidos = "apellido 12",
                            Direccion = "Direccion 12",
                            Email = "Email@dominio.com 12",
                            Nombre = "usuario 12"
                        },
                        new
                        {
                            IdUsuario = 13,
                            Apellidos = "apellido 13",
                            Direccion = "Direccion 13",
                            Email = "Email@dominio.com 13",
                            Nombre = "usuario 13"
                        },
                        new
                        {
                            IdUsuario = 14,
                            Apellidos = "apellido 14",
                            Direccion = "Direccion 14",
                            Email = "Email@dominio.com 14",
                            Nombre = "usuario 14"
                        },
                        new
                        {
                            IdUsuario = 15,
                            Apellidos = "apellido 15",
                            Direccion = "Direccion 15",
                            Email = "Email@dominio.com 15",
                            Nombre = "usuario 15"
                        },
                        new
                        {
                            IdUsuario = 16,
                            Apellidos = "apellido 16",
                            Direccion = "Direccion 16",
                            Email = "Email@dominio.com 16",
                            Nombre = "usuario 16"
                        },
                        new
                        {
                            IdUsuario = 17,
                            Apellidos = "apellido 17",
                            Direccion = "Direccion 17",
                            Email = "Email@dominio.com 17",
                            Nombre = "usuario 17"
                        },
                        new
                        {
                            IdUsuario = 18,
                            Apellidos = "apellido 18",
                            Direccion = "Direccion 18",
                            Email = "Email@dominio.com 18",
                            Nombre = "usuario 18"
                        },
                        new
                        {
                            IdUsuario = 19,
                            Apellidos = "apellido 19",
                            Direccion = "Direccion 19",
                            Email = "Email@dominio.com 19",
                            Nombre = "usuario 19"
                        },
                        new
                        {
                            IdUsuario = 20,
                            Apellidos = "apellido 20",
                            Direccion = "Direccion 20",
                            Email = "Email@dominio.com 20",
                            Nombre = "usuario 20"
                        },
                        new
                        {
                            IdUsuario = 21,
                            Apellidos = "apellido 21",
                            Direccion = "Direccion 21",
                            Email = "Email@dominio.com 21",
                            Nombre = "usuario 21"
                        },
                        new
                        {
                            IdUsuario = 22,
                            Apellidos = "apellido 22",
                            Direccion = "Direccion 22",
                            Email = "Email@dominio.com 22",
                            Nombre = "usuario 22"
                        },
                        new
                        {
                            IdUsuario = 23,
                            Apellidos = "apellido 23",
                            Direccion = "Direccion 23",
                            Email = "Email@dominio.com 23",
                            Nombre = "usuario 23"
                        },
                        new
                        {
                            IdUsuario = 24,
                            Apellidos = "apellido 24",
                            Direccion = "Direccion 24",
                            Email = "Email@dominio.com 24",
                            Nombre = "usuario 24"
                        },
                        new
                        {
                            IdUsuario = 25,
                            Apellidos = "apellido 25",
                            Direccion = "Direccion 25",
                            Email = "Email@dominio.com 25",
                            Nombre = "usuario 25"
                        },
                        new
                        {
                            IdUsuario = 26,
                            Apellidos = "apellido 26",
                            Direccion = "Direccion 26",
                            Email = "Email@dominio.com 26",
                            Nombre = "usuario 26"
                        },
                        new
                        {
                            IdUsuario = 27,
                            Apellidos = "apellido 27",
                            Direccion = "Direccion 27",
                            Email = "Email@dominio.com 27",
                            Nombre = "usuario 27"
                        },
                        new
                        {
                            IdUsuario = 28,
                            Apellidos = "apellido 28",
                            Direccion = "Direccion 28",
                            Email = "Email@dominio.com 28",
                            Nombre = "usuario 28"
                        },
                        new
                        {
                            IdUsuario = 29,
                            Apellidos = "apellido 29",
                            Direccion = "Direccion 29",
                            Email = "Email@dominio.com 29",
                            Nombre = "usuario 29"
                        },
                        new
                        {
                            IdUsuario = 30,
                            Apellidos = "apellido 30",
                            Direccion = "Direccion 30",
                            Email = "Email@dominio.com 30",
                            Nombre = "usuario 30"
                        },
                        new
                        {
                            IdUsuario = 31,
                            Apellidos = "apellido 31",
                            Direccion = "Direccion 31",
                            Email = "Email@dominio.com 31",
                            Nombre = "usuario 31"
                        },
                        new
                        {
                            IdUsuario = 32,
                            Apellidos = "apellido 32",
                            Direccion = "Direccion 32",
                            Email = "Email@dominio.com 32",
                            Nombre = "usuario 32"
                        },
                        new
                        {
                            IdUsuario = 33,
                            Apellidos = "apellido 33",
                            Direccion = "Direccion 33",
                            Email = "Email@dominio.com 33",
                            Nombre = "usuario 33"
                        },
                        new
                        {
                            IdUsuario = 34,
                            Apellidos = "apellido 34",
                            Direccion = "Direccion 34",
                            Email = "Email@dominio.com 34",
                            Nombre = "usuario 34"
                        },
                        new
                        {
                            IdUsuario = 35,
                            Apellidos = "apellido 35",
                            Direccion = "Direccion 35",
                            Email = "Email@dominio.com 35",
                            Nombre = "usuario 35"
                        },
                        new
                        {
                            IdUsuario = 36,
                            Apellidos = "apellido 36",
                            Direccion = "Direccion 36",
                            Email = "Email@dominio.com 36",
                            Nombre = "usuario 36"
                        },
                        new
                        {
                            IdUsuario = 37,
                            Apellidos = "apellido 37",
                            Direccion = "Direccion 37",
                            Email = "Email@dominio.com 37",
                            Nombre = "usuario 37"
                        },
                        new
                        {
                            IdUsuario = 38,
                            Apellidos = "apellido 38",
                            Direccion = "Direccion 38",
                            Email = "Email@dominio.com 38",
                            Nombre = "usuario 38"
                        },
                        new
                        {
                            IdUsuario = 39,
                            Apellidos = "apellido 39",
                            Direccion = "Direccion 39",
                            Email = "Email@dominio.com 39",
                            Nombre = "usuario 39"
                        },
                        new
                        {
                            IdUsuario = 40,
                            Apellidos = "apellido 40",
                            Direccion = "Direccion 40",
                            Email = "Email@dominio.com 40",
                            Nombre = "usuario 40"
                        },
                        new
                        {
                            IdUsuario = 41,
                            Apellidos = "apellido 41",
                            Direccion = "Direccion 41",
                            Email = "Email@dominio.com 41",
                            Nombre = "usuario 41"
                        },
                        new
                        {
                            IdUsuario = 42,
                            Apellidos = "apellido 42",
                            Direccion = "Direccion 42",
                            Email = "Email@dominio.com 42",
                            Nombre = "usuario 42"
                        },
                        new
                        {
                            IdUsuario = 43,
                            Apellidos = "apellido 43",
                            Direccion = "Direccion 43",
                            Email = "Email@dominio.com 43",
                            Nombre = "usuario 43"
                        },
                        new
                        {
                            IdUsuario = 44,
                            Apellidos = "apellido 44",
                            Direccion = "Direccion 44",
                            Email = "Email@dominio.com 44",
                            Nombre = "usuario 44"
                        },
                        new
                        {
                            IdUsuario = 45,
                            Apellidos = "apellido 45",
                            Direccion = "Direccion 45",
                            Email = "Email@dominio.com 45",
                            Nombre = "usuario 45"
                        },
                        new
                        {
                            IdUsuario = 46,
                            Apellidos = "apellido 46",
                            Direccion = "Direccion 46",
                            Email = "Email@dominio.com 46",
                            Nombre = "usuario 46"
                        },
                        new
                        {
                            IdUsuario = 47,
                            Apellidos = "apellido 47",
                            Direccion = "Direccion 47",
                            Email = "Email@dominio.com 47",
                            Nombre = "usuario 47"
                        },
                        new
                        {
                            IdUsuario = 48,
                            Apellidos = "apellido 48",
                            Direccion = "Direccion 48",
                            Email = "Email@dominio.com 48",
                            Nombre = "usuario 48"
                        },
                        new
                        {
                            IdUsuario = 49,
                            Apellidos = "apellido 49",
                            Direccion = "Direccion 49",
                            Email = "Email@dominio.com 49",
                            Nombre = "usuario 49"
                        },
                        new
                        {
                            IdUsuario = 50,
                            Apellidos = "apellido 50",
                            Direccion = "Direccion 50",
                            Email = "Email@dominio.com 50",
                            Nombre = "usuario 50"
                        },
                        new
                        {
                            IdUsuario = 51,
                            Apellidos = "apellido 51",
                            Direccion = "Direccion 51",
                            Email = "Email@dominio.com 51",
                            Nombre = "usuario 51"
                        },
                        new
                        {
                            IdUsuario = 52,
                            Apellidos = "apellido 52",
                            Direccion = "Direccion 52",
                            Email = "Email@dominio.com 52",
                            Nombre = "usuario 52"
                        },
                        new
                        {
                            IdUsuario = 53,
                            Apellidos = "apellido 53",
                            Direccion = "Direccion 53",
                            Email = "Email@dominio.com 53",
                            Nombre = "usuario 53"
                        },
                        new
                        {
                            IdUsuario = 54,
                            Apellidos = "apellido 54",
                            Direccion = "Direccion 54",
                            Email = "Email@dominio.com 54",
                            Nombre = "usuario 54"
                        },
                        new
                        {
                            IdUsuario = 55,
                            Apellidos = "apellido 55",
                            Direccion = "Direccion 55",
                            Email = "Email@dominio.com 55",
                            Nombre = "usuario 55"
                        },
                        new
                        {
                            IdUsuario = 56,
                            Apellidos = "apellido 56",
                            Direccion = "Direccion 56",
                            Email = "Email@dominio.com 56",
                            Nombre = "usuario 56"
                        },
                        new
                        {
                            IdUsuario = 57,
                            Apellidos = "apellido 57",
                            Direccion = "Direccion 57",
                            Email = "Email@dominio.com 57",
                            Nombre = "usuario 57"
                        },
                        new
                        {
                            IdUsuario = 58,
                            Apellidos = "apellido 58",
                            Direccion = "Direccion 58",
                            Email = "Email@dominio.com 58",
                            Nombre = "usuario 58"
                        },
                        new
                        {
                            IdUsuario = 59,
                            Apellidos = "apellido 59",
                            Direccion = "Direccion 59",
                            Email = "Email@dominio.com 59",
                            Nombre = "usuario 59"
                        },
                        new
                        {
                            IdUsuario = 60,
                            Apellidos = "apellido 60",
                            Direccion = "Direccion 60",
                            Email = "Email@dominio.com 60",
                            Nombre = "usuario 60"
                        },
                        new
                        {
                            IdUsuario = 61,
                            Apellidos = "apellido 61",
                            Direccion = "Direccion 61",
                            Email = "Email@dominio.com 61",
                            Nombre = "usuario 61"
                        },
                        new
                        {
                            IdUsuario = 62,
                            Apellidos = "apellido 62",
                            Direccion = "Direccion 62",
                            Email = "Email@dominio.com 62",
                            Nombre = "usuario 62"
                        },
                        new
                        {
                            IdUsuario = 63,
                            Apellidos = "apellido 63",
                            Direccion = "Direccion 63",
                            Email = "Email@dominio.com 63",
                            Nombre = "usuario 63"
                        },
                        new
                        {
                            IdUsuario = 64,
                            Apellidos = "apellido 64",
                            Direccion = "Direccion 64",
                            Email = "Email@dominio.com 64",
                            Nombre = "usuario 64"
                        },
                        new
                        {
                            IdUsuario = 65,
                            Apellidos = "apellido 65",
                            Direccion = "Direccion 65",
                            Email = "Email@dominio.com 65",
                            Nombre = "usuario 65"
                        },
                        new
                        {
                            IdUsuario = 66,
                            Apellidos = "apellido 66",
                            Direccion = "Direccion 66",
                            Email = "Email@dominio.com 66",
                            Nombre = "usuario 66"
                        },
                        new
                        {
                            IdUsuario = 67,
                            Apellidos = "apellido 67",
                            Direccion = "Direccion 67",
                            Email = "Email@dominio.com 67",
                            Nombre = "usuario 67"
                        },
                        new
                        {
                            IdUsuario = 68,
                            Apellidos = "apellido 68",
                            Direccion = "Direccion 68",
                            Email = "Email@dominio.com 68",
                            Nombre = "usuario 68"
                        },
                        new
                        {
                            IdUsuario = 69,
                            Apellidos = "apellido 69",
                            Direccion = "Direccion 69",
                            Email = "Email@dominio.com 69",
                            Nombre = "usuario 69"
                        },
                        new
                        {
                            IdUsuario = 70,
                            Apellidos = "apellido 70",
                            Direccion = "Direccion 70",
                            Email = "Email@dominio.com 70",
                            Nombre = "usuario 70"
                        },
                        new
                        {
                            IdUsuario = 71,
                            Apellidos = "apellido 71",
                            Direccion = "Direccion 71",
                            Email = "Email@dominio.com 71",
                            Nombre = "usuario 71"
                        },
                        new
                        {
                            IdUsuario = 72,
                            Apellidos = "apellido 72",
                            Direccion = "Direccion 72",
                            Email = "Email@dominio.com 72",
                            Nombre = "usuario 72"
                        },
                        new
                        {
                            IdUsuario = 73,
                            Apellidos = "apellido 73",
                            Direccion = "Direccion 73",
                            Email = "Email@dominio.com 73",
                            Nombre = "usuario 73"
                        },
                        new
                        {
                            IdUsuario = 74,
                            Apellidos = "apellido 74",
                            Direccion = "Direccion 74",
                            Email = "Email@dominio.com 74",
                            Nombre = "usuario 74"
                        },
                        new
                        {
                            IdUsuario = 75,
                            Apellidos = "apellido 75",
                            Direccion = "Direccion 75",
                            Email = "Email@dominio.com 75",
                            Nombre = "usuario 75"
                        },
                        new
                        {
                            IdUsuario = 76,
                            Apellidos = "apellido 76",
                            Direccion = "Direccion 76",
                            Email = "Email@dominio.com 76",
                            Nombre = "usuario 76"
                        },
                        new
                        {
                            IdUsuario = 77,
                            Apellidos = "apellido 77",
                            Direccion = "Direccion 77",
                            Email = "Email@dominio.com 77",
                            Nombre = "usuario 77"
                        },
                        new
                        {
                            IdUsuario = 78,
                            Apellidos = "apellido 78",
                            Direccion = "Direccion 78",
                            Email = "Email@dominio.com 78",
                            Nombre = "usuario 78"
                        },
                        new
                        {
                            IdUsuario = 79,
                            Apellidos = "apellido 79",
                            Direccion = "Direccion 79",
                            Email = "Email@dominio.com 79",
                            Nombre = "usuario 79"
                        },
                        new
                        {
                            IdUsuario = 80,
                            Apellidos = "apellido 80",
                            Direccion = "Direccion 80",
                            Email = "Email@dominio.com 80",
                            Nombre = "usuario 80"
                        },
                        new
                        {
                            IdUsuario = 81,
                            Apellidos = "apellido 81",
                            Direccion = "Direccion 81",
                            Email = "Email@dominio.com 81",
                            Nombre = "usuario 81"
                        },
                        new
                        {
                            IdUsuario = 82,
                            Apellidos = "apellido 82",
                            Direccion = "Direccion 82",
                            Email = "Email@dominio.com 82",
                            Nombre = "usuario 82"
                        },
                        new
                        {
                            IdUsuario = 83,
                            Apellidos = "apellido 83",
                            Direccion = "Direccion 83",
                            Email = "Email@dominio.com 83",
                            Nombre = "usuario 83"
                        },
                        new
                        {
                            IdUsuario = 84,
                            Apellidos = "apellido 84",
                            Direccion = "Direccion 84",
                            Email = "Email@dominio.com 84",
                            Nombre = "usuario 84"
                        },
                        new
                        {
                            IdUsuario = 85,
                            Apellidos = "apellido 85",
                            Direccion = "Direccion 85",
                            Email = "Email@dominio.com 85",
                            Nombre = "usuario 85"
                        },
                        new
                        {
                            IdUsuario = 86,
                            Apellidos = "apellido 86",
                            Direccion = "Direccion 86",
                            Email = "Email@dominio.com 86",
                            Nombre = "usuario 86"
                        },
                        new
                        {
                            IdUsuario = 87,
                            Apellidos = "apellido 87",
                            Direccion = "Direccion 87",
                            Email = "Email@dominio.com 87",
                            Nombre = "usuario 87"
                        },
                        new
                        {
                            IdUsuario = 88,
                            Apellidos = "apellido 88",
                            Direccion = "Direccion 88",
                            Email = "Email@dominio.com 88",
                            Nombre = "usuario 88"
                        },
                        new
                        {
                            IdUsuario = 89,
                            Apellidos = "apellido 89",
                            Direccion = "Direccion 89",
                            Email = "Email@dominio.com 89",
                            Nombre = "usuario 89"
                        },
                        new
                        {
                            IdUsuario = 90,
                            Apellidos = "apellido 90",
                            Direccion = "Direccion 90",
                            Email = "Email@dominio.com 90",
                            Nombre = "usuario 90"
                        },
                        new
                        {
                            IdUsuario = 91,
                            Apellidos = "apellido 91",
                            Direccion = "Direccion 91",
                            Email = "Email@dominio.com 91",
                            Nombre = "usuario 91"
                        },
                        new
                        {
                            IdUsuario = 92,
                            Apellidos = "apellido 92",
                            Direccion = "Direccion 92",
                            Email = "Email@dominio.com 92",
                            Nombre = "usuario 92"
                        },
                        new
                        {
                            IdUsuario = 93,
                            Apellidos = "apellido 93",
                            Direccion = "Direccion 93",
                            Email = "Email@dominio.com 93",
                            Nombre = "usuario 93"
                        },
                        new
                        {
                            IdUsuario = 94,
                            Apellidos = "apellido 94",
                            Direccion = "Direccion 94",
                            Email = "Email@dominio.com 94",
                            Nombre = "usuario 94"
                        },
                        new
                        {
                            IdUsuario = 95,
                            Apellidos = "apellido 95",
                            Direccion = "Direccion 95",
                            Email = "Email@dominio.com 95",
                            Nombre = "usuario 95"
                        },
                        new
                        {
                            IdUsuario = 96,
                            Apellidos = "apellido 96",
                            Direccion = "Direccion 96",
                            Email = "Email@dominio.com 96",
                            Nombre = "usuario 96"
                        },
                        new
                        {
                            IdUsuario = 97,
                            Apellidos = "apellido 97",
                            Direccion = "Direccion 97",
                            Email = "Email@dominio.com 97",
                            Nombre = "usuario 97"
                        },
                        new
                        {
                            IdUsuario = 98,
                            Apellidos = "apellido 98",
                            Direccion = "Direccion 98",
                            Email = "Email@dominio.com 98",
                            Nombre = "usuario 98"
                        },
                        new
                        {
                            IdUsuario = 99,
                            Apellidos = "apellido 99",
                            Direccion = "Direccion 99",
                            Email = "Email@dominio.com 99",
                            Nombre = "usuario 99"
                        },
                        new
                        {
                            IdUsuario = 100,
                            Apellidos = "apellido 100",
                            Direccion = "Direccion 100",
                            Email = "Email@dominio.com 100",
                            Nombre = "usuario 100"
                        });
                });

            modelBuilder.Entity("ReservasCore6.Models.Reserva", b =>
                {
                    b.HasOne("ReservasCore6.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("IdHotel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCore6.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
